set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_CLK_N]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_CLK_N]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_CLK_P]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_CLK_P]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_N[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_N[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_N[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_N[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_N[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_N[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_P[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_P[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_P[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_P[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_P[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet TMDS_DATA_P[2]]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet TMDS_CLK_N]]
