# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7 provided/mb_usb_hdmi_top.xdc

# Block Designs: bd/hdmi_block/hdmi_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block || ORIG_REF_NAME==hdmi_block} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_microblaze_0_0/hdmi_block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_microblaze_0_0 || ORIG_REF_NAME==hdmi_block_microblaze_0_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_dlmb_v10_0/hdmi_block_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_dlmb_v10_0 || ORIG_REF_NAME==hdmi_block_dlmb_v10_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_ilmb_v10_0/hdmi_block_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_ilmb_v10_0 || ORIG_REF_NAME==hdmi_block_ilmb_v10_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_dlmb_bram_if_cntlr_0/hdmi_block_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_ilmb_bram_if_cntlr_0/hdmi_block_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_lmb_bram_0/hdmi_block_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_lmb_bram_0 || ORIG_REF_NAME==hdmi_block_lmb_bram_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_xbar_0/hdmi_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_xbar_0 || ORIG_REF_NAME==hdmi_block_xbar_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_microblaze_0_axi_periph_0/hdmi_block_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hdmi_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_microblaze_0_axi_intc_0/hdmi_block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hdmi_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_mdm_1_0/hdmi_block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_mdm_1_0 || ORIG_REF_NAME==hdmi_block_mdm_1_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_clk_wiz_1_0/hdmi_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_clk_wiz_1_0 || ORIG_REF_NAME==hdmi_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_rst_clk_wiz_1_100M_0/hdmi_block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==hdmi_block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_axi_uartlite_0_0/hdmi_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_axi_uartlite_0_0 || ORIG_REF_NAME==hdmi_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/hdmi_block/ip/hdmi_block_hdmi_text_controller_0_0/hdmi_block_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_block_hdmi_text_controller_0_0 || ORIG_REF_NAME==hdmi_block_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab7/lab7.gen/sources_1/bd/hdmi_block/hdmi_block_ooc.xdc
