# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab7/lab7.srcs/sources_1/bd/hdmi_block/ip/hdmi_block_xbar_0/hdmi_block_xbar_0.xci
# IP: The module: 'hdmi_block_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab7/lab7.gen/sources_1/bd/hdmi_block/ip/hdmi_block_xbar_0/hdmi_block_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_block_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab7/lab7.srcs/sources_1/bd/hdmi_block/ip/hdmi_block_xbar_0/hdmi_block_xbar_0.xci
# IP: The module: 'hdmi_block_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab7/lab7.gen/sources_1/bd/hdmi_block/ip/hdmi_block_xbar_0/hdmi_block_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_block_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
