# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0.xci
# IP: The module: 'mb_block_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0.xci
# IP: The module: 'mb_block_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/user/OneDrive/Documents/ECE385/ECE385/lab6/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
